### ISSUE TITLE
composer version outdated → plugin installed in wrong folder

### ISSUE THREAD

**Issue by tmmmmm** [fendinger/kirby3-consent-gate#3]
Installation via composer installs the package into {site}/vendor/fendinger/ instead of {site}/site/plugins/ which does not work. I guess this is due to the outdated composer.json on packagist which has been updated in the git. Consider a new tag/release and/or auto-updating the package?

**Comment by andreasotto** [comment]
+1 not going to fix it?

**Comment by fendinger** [comment]
hi guys - the folder issue with composer is fixed.
